### ISSUE TITLE
Printout

### ISSUE THREAD

**Issue by blazedd** [techlahoma/Event-Intro#4]
We need a laminated printout for usergroups to use.

**Comment by blazedd** [comment]
I'd like to claim this issue.

**Comment by kacollins** [comment]
What's the plan for this? User group leaders ask for the link to the intro pretty often, and some don't even seem to be aware of it.

Could we just print a couple of copies and put them in sheet protectors at StarSpace46 and 36°N? The text changes often enough that needing lamination is probably too much of a hassle.

**Comment by kacollins** [comment]
I'm going to take ownership of this issue and leave a copy of the event intro at StarSpace46.

**Comment by kacollins** [comment]
Done!
