### ISSUE TITLE
Add CoC Blurb to Intro

### ISSUE THREAD

**Issue by zarthross** [techlahoma/Event-Intro#7]
We need to have a quick blurb saying we have a CoC and you should read it.

Suggestions on wording would be helpful.

"Hey, and BTW, we have a code of conduct you should checkout.  Cliffnotes: Be awesome to each other" <-- obvious joking.... but maybe?

**Comment by kacollins** [comment]
Maybe just mention that the [CoC](https://www.techlahoma.org/code-of-conduct) and [Incident Report Form](https://www.techlahoma.org/incident) are on the Techlahoma website

**Comment by Avasond** [comment]
Hello! I would advise against using phrases like "Be awesome to each other" 
I interpret that as a pretty big red flag that an organization doesn't take their CoC seriously and may not enforce it. This is what we have in the Incidents form: 

> It's extremely important to us that our members feel safe and respected at our events. If you have an issue with someone's behaviour at a Techlahoma Foundation event, please let us know via the Incident Report form or one of the other methods provided on our website so we can take action immediately.

**Comment by kacollins** [comment]
I agree about the "be awesome" phrasing. I'll add this wording to the event intro, and user group leaders can say it in their own words!

**Comment by kacollins** [comment]
Got it added. Thanks, @Avasond and @zarthross! I'm not sure if I put it in the best place in the intro. Feel free to move it if you'd like.
